spring:
  datasource:
    url: jdbc:h2:mem:vdfdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        default_schema: PUBLIC
  h2:
    console:
      enabled: true
      path: /h2-console
  flyway:
    enabled: false

server:
  port: 8081

logging:
  level:
    com.sidbi.vdf: DEBUG
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG