spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/vdf
    username: vdf
    password: vdf

logging:
  level:
    com.sidbi.vdf: DEBUG
    org.hibernate.SQL: DEBUG
